export const IRREGULAR_WORDS: Record<string, string[]> = {
    // Verbs
    "abide": ["abode", "abided", "abiding", "abides"],
    "arise": ["arose", "arisen", "arising", "arises"],
    "awake": ["awoke", "awaked", "awaking", "awakes"],
    "be": ["am", "is", "are", "was", "were", "been", "being", "'m", "'s", "'re", "isn't", "aren't", "wasn't", "weren't"],
    "bear": ["bore", "born", "borne", "bearing", "bears"],
    "beat": ["beat", "beaten", "beating", "beats"],
    "become": ["became", "becoming", "becomes"],
    "begin": ["began", "begun", "beginning", "begins"],
    "bend": ["bent", "bending", "bends"],
    "bet": ["bet", "betted", "betting", "bets"],
    "bid": ["bid", "bade", "bidden", "bidding", "bids"],
    "bind": ["bound", "binding", "binds"],
    "bite": ["bit", "bitten", "biting", "bites"],
    "bleed": ["bled", "bleeding", "bleeds"],
    "blow": ["blew", "blown", "blowing", "blows"],
    "break": ["broke", "broken", "breaking", "breaks"],
    "breed": ["bred", "breeding", "breeds"],
    "bring": ["brought", "bringing", "brings"],
    "build": ["built", "building", "builds"],
    "burn": ["burnt", "burned", "burning", "burns"],
    "burst": ["burst", "bursting", "bursts"],
    "buy": ["bought", "buying", "buys"],
    "cast": ["cast", "casting", "casts"],
    "catch": ["caught", "catching", "catches"],
    "choose": ["chose", "chosen", "choosing", "chooses"],
    "cling": ["clung", "clinging", "clings"],
    "come": ["came", "coming", "comes"],
    "cost": ["cost", "costing", "costs"],
    "creep": ["crept", "creeping", "creeps"],
    "cut": ["cut", "cutting", "cuts"],
    "deal": ["dealt", "dealing", "deals"],
    "dig": ["dug", "digging", "digs"],
    "do": ["did", "done", "doing", "does", "don't", "doesn't", "didn't"],
    "draw": ["drew", "drawn", "drawing", "draws"],
    "dream": ["dreamt", "dreamed", "dreaming", "dreams"],
    "drink": ["drank", "drunk", "drinking", "drinks"],
    "drive": ["drove", "driven", "driving", "drives"],
    "dwell": ["dwelt", "dwelled", "dwelling", "dwells"],
    "eat": ["ate", "eaten", "eating", "eats"],
    "fall": ["fell", "fallen", "falling", "falls"],
    "feed": ["fed", "feeding", "feeds"],
    "feel": ["felt", "feeling", "feels"],
    "fight": ["fought", "fighting", "fights"],
    "find": ["found", "finding", "finds"],
    "flee": ["fled", "fleeing", "flees"],
    "fling": ["flung", "flinging", "flings"],
    "fly": ["flew", "flown", "flying", "flies"],
    "forbid": ["forbade", "forbidden", "forbidding", "forbids"],
    "forget": ["forgot", "forgotten", "forgetting", "forgets"],
    "forgive": ["forgave", "forgiven", "forgiving", "forgives"],
    "freeze": ["froze", "frozen", "freezing", "freezes"],
    "get": ["got", "gotten", "getting", "gets"],
    "give": ["gave", "given", "giving", "gives"],
    "go": ["went", "gone", "going", "goes"],
    "grind": ["ground", "grinding", "grinds"],
    "grow": ["grew", "grown", "growing", "grows"],
    "hang": ["hung", "hanged", "hanging", "hangs"],
    "have": ["had", "has", "having", "'ve", "hasn't", "haven't", "hadn't"],
    "hear": ["heard", "hearing", "hears"],
    "hide": ["hid", "hidden", "hiding", "hides"],
    "hit": ["hit", "hitting", "hits"],
    "hold": ["held", "holding", "holds"],
    "hurt": ["hurt", "hurting", "hurts"],
    "keep": ["kept", "keeping", "keeps"],
    "kneel": ["knelt", "kneeled", "kneeling", "kneels"],
    "know": ["knew", "known", "knowing", "knows"],
    "lay": ["laid", "laying", "lays"],
    "lead": ["led", "leading", "leads"],
    "lean": ["leant", "leaned", "leaning", "leans"],
    "leap": ["leapt", "leaped", "leaping", "leaps"],
    "learn": ["learnt", "learned", "learning", "learns"],
    "leave": ["left", "leaving", "leaves"],
    "lend": ["lent", "lending", "lends"],
    "let": ["let", "letting", "lets"],
    "lie": ["lay", "lain", "lying", "lies"],
    "light": ["lit", "lighted", "lighting", "lights"],
    "lose": ["lost", "losing", "loses"],
    "make": ["made", "making", "makes"],
    "mean": ["meant", "meaning", "means"],
    "meet": ["met", "meeting", "meets"],
    "mow": ["mowed", "mown", "mowing", "mows"],
    "pay": ["paid", "paying", "pays"],
    "prove": ["proved", "proven", "proving", "proves"],
    "put": ["put", "putting", "puts"],
    "read": ["read", "reading", "reads"],
    "ride": ["rode", "ridden", "riding", "rides"],
    "ring": ["rang", "rung", "ringing", "rings"],
    "rise": ["rose", "risen", "rising", "rises"],
    "run": ["ran", "running", "runs"],
    "say": ["said", "saying", "says"],
    "saw": ["sawed", "sawn", "sawing", "saws"],
    "see": ["saw", "seen", "seeing", "sees"],
    "sell": ["sold", "selling", "sells"],
    "send": ["sent", "sending", "sends"],
    "set": ["set", "setting", "sets"],
    "sew": ["sewed", "sewn", "sewing", "sews"],
    "shake": ["shook", "shaken", "shaking", "shakes"],
    "shear": ["sheared", "shorn", "shearing", "shears"],
    "shine": ["shone", "shined", "shining", "shines"],
    "shoot": ["shot", "shooting", "shoots"],
    "show": ["showed", "shown", "showing", "shows"],
    "shrink": ["shrank", "shrunk", "shrinking", "shrinks"],
    "shut": ["shut", "shutting", "shuts"],
    "sing": ["sang", "sung", "singing", "sings"],
    "sink": ["sank", "sunk", "sinking", "sinks"],
    "sit": ["sat", "sitting", "sits"],
    "sleep": ["slept", "sleeping", "sleeps"],
    "slide": ["slid", "sliding", "slides"],
    "sling": ["slung", "slinging", "slings"],
    "smell": ["smelt", "smelled", "smelling", "smells"],
    "sow": ["sowed", "sown", "sowing", "sows"],
    "speak": ["spoke", "spoken", "speaking", "speaks"],
    "speed": ["sped", "speeded", "speeding", "speeds"],
    "spell": ["spelt", "spelled", "spelling", "spells"],
    "spend": ["spent", "spending", "spends"],
    "spin": ["spun", "spinning", "spins"],
    "spit": ["spat", "spitted", "spitting", "spits"],
    "split": ["split", "splitting", "splits"],
    "spoil": ["spoilt", "spoiled", "spoiling", "spoils"],
    "spread": ["spread", "spreading", "spreads"],
    "spring": ["sprang", "sprung", "springing", "springs"],
    "stand": ["stood", "standing", "stands"],
    "steal": ["stole", "stolen", "stealing", "steals"],
    "stick": ["stuck", "sticking", "sticks"],
    "sting": ["stung", "stinging", "stings"],
    "strew": ["strewed", "strewn", "strewing", "strews"],
    "stride": ["strode", "stridden", "striding", "strides"],
    "strike": ["struck", "striking", "strikes"],
    "strive": ["strove", "striven", "striving", "strives"],
    "swear": ["swore", "sworn", "swearing", "swears"],
    "sweep": ["swept", "sweeping", "sweeps"],
    "swell": ["swelled", "swollen", "swelling", "swells"],
    "swim": ["swam", "swum", "swimming", "swims"],
    "swing": ["swung", "swinging", "swings"],
    "take": ["took", "taken", "taking", "takes"],
    "teach": ["taught", "teaching", "teaches"],
    "tear": ["tore", "torn", "tearing", "tears"],
    "tell": ["told", "telling", "tells"],
    "think": ["thought", "thinking", "thinks"],
    "throw": ["threw", "thrown", "throwing", "throws"],
    "tread": ["trod", "trodden", "treading", "treads"],
    "understand": ["understood", "understanding", "understands"],
    "wake": ["woke", "waken", "waking", "wakes"],
    "wear": ["wore", "worn", "wearing", "wears"],
    "weave": ["wove", "woven", "weaving", "weaves"],
    "wed": ["wed", "wedded", "wedding", "weds"],
    "wet": ["wet", "wetted", "wetting", "wets"],
    "win": ["won", "winning", "wins"],
    "wind": ["wound", "winding", "winds"],
    "write": ["wrote", "written", "writing", "writes"],

    // Additional Contractions
    "can": ["can't", "cannot"],
    "will": ["won't", "'ll"],
    "shall": ["shan't"],
    "would": ["wouldn't", "'d"],
    "should": ["shouldn't"],
    "could": ["couldn't"],
    "must": ["mustn't"],

    // Irregular Nouns
    "man": ["men"],
    "woman": ["women"],
    "child": ["children"],
    "foot": ["feet"],
    "tooth": ["teeth"],
    "goose": ["geese"],
    "mouse": ["mice"],
    "person": ["people"],
    "ox": ["oxen"],
    "leaf": ["leaves"],
    "knife": ["knives"],
    "wife": ["wives"],
    "life": ["lives"],
    "half": ["halves"],
    "shelf": ["shelves"],
    "thief": ["thieves"],
    "wolf": ["wolves"],

    // Irregular Adjectives
    "good": ["better", "best"],
    "bad": ["worse", "worst"],
    "far": ["farther", "farthest", "further", "furthest"],
    "little": ["less", "least"],
    "many": ["more", "most"],
    "much": ["more", "most"]
};

